[package]
name = "zsnake"
version = "0.1.0"
authors = ["David Wylie <david.wylie@zuhlke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"